import "./render/render-locations.js";
import "./questions-block.js";
import "./render/footer.js";
import "./swiper.js";
import "./localization.js";
import "./chart.js";
import "./utils/animations.js";
import "./navbar.js";
import "./utils/modal-ask.js"
import "./send-email.js";